# Generated by Django 2.2.6 on 2020-04-05 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='blogpost_files/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blogpost_files/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blogpost_files/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blogpost_files/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='blogpost_files/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='blogpost_files/')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='blogpost_files/')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='blogpost_files/')),
                ('category', models.CharField(help_text='Lifestyle, Food, Fashion ', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
